### PR TITLE
Document cellfinder-core release steps

### LINKED ISSUE #50: Document release process
I'm about to do a release, and document the steps needed at https://github.com/brainglobe/bg-gitbook/blob/master/development.md

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/brainglobe/cellfinder-core/issues/50

### CODE REVIEW

**Review by paddyroddy — APPROVED** [review]
Looks great

**Comment by adamltyson** [comment]
Hey @dstansby, all looks good, but could you add the concept of `bump2version release` (see [docs](https://docs.brainglobe.info/cellfinder/contributing/dev-conventions#versioning))? The workflow should be as simple as:

```
bump2version <type>
bump2version rc (if needed)
bump2version release
```

**Comment by adamltyson** [comment]
As with the other developer docs, I think we should move this into a single contribution guide (https://github.com/brainglobe/cellfinder/issues/332), but making sure to emphasise the dependency tests outlined here.

**Comment by adamltyson** [comment]
This doc has been moved into a central BG doc:
https://github.com/brainglobe/.github/pull/2

**Pull request closed without merging**
