### PR TITLE
UCL RSD suggestions for development workflow

### PR DESCRIPTION
**Pull request by alessandrofelder**
This PR adds the conventions the UCL Research Software Development Team working on `cellfinder-napari` and `brainreg-napari` intend to follow for this project. Adjustments/feedback welcome - we don't want to impose on existing practices and can adapt!

@dpshelio @dstansby @paddyroddy we didn't talk about squashing commits before merging or not. What would you suggest?

### CODE REVIEW

**Comment by adamltyson** [comment]
I’d rather all commits were squashed before merging.

**Comment by adamltyson** [comment]
All conventions look good to me 👍

**Comment by vigji** [comment]
Everything looks good to me!

**Comment by dstansby** [comment]
I am used to not squashing commits before merging, because you lose information about how a given PR was developed, especially if it was a large PR.

**Comment by paddyroddy** [comment]
> I am used to not squashing commits before merging, because you lose information about how a given PR was developed, especially if it was a large PR.

Anyone really interested can still go to the PR and see what went into it. I don't normally do it myself, but somewhere I worked the default button on PRs was always "squash and merge"

**Comment by vigji** [comment]
Agreed, with informative branch names PR merges should be self explanatory, and easy to dig further into if necessary.

**Comment by adamltyson** [comment]
This looks fine, but I was thinking we should move all of these developer docs into a single contribution guide (see https://github.com/brainglobe/cellfinder/issues/332)

**Comment by adamltyson** [comment]
This doc has been moved into a central BG doc:
https://github.com/brainglobe/.github/pull/2

**Pull request closed without merging**
